### ISSUE TITLE
大佬你好我想请教一下怎么把历史记录单独分出一个页面然后还能同步首页的抽取数据呢我现在分出来了但是没法同步首页的抽取数据

### ISSUE THREAD

**Issue by 7h7h7h7h7h** [entireyu/what-to-eat-now#2]

**Comment by entireyu** [comment]
你好，可以尝试把信息存储缓存到用户本地
具体可以参考API
https://developers.weixin.qq.com/miniprogram/dev/api/storage/wx.setStorageSync.html

**Comment by 7h7h7h7h7h** [comment]
大佬如果有空的话可以说的更详细一点吗谢谢谢谢非常需要
